In [1]:
import numpy as np


In [2]:
arr=np.array([[1,2,3,45,5]])

In [3]:
arr

array([[ 1,  2,  3, 45,  5]])

In [4]:
arr.shape

(1, 5)

In [5]:
arr.dtype

dtype('int32')

#here is my tutruorial for numpy

**fwfwffsf***

In [6]:
ar=np.zeros((1,5))

In [7]:
ar

array([[0., 0., 0., 0., 0.]])

In [8]:
are=np.zeros((5))

In [9]:
are

array([0., 0., 0., 0., 0.])

In [10]:
are=np.zeros((4,4))
print(are)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
are[1,1]

0.0

In [12]:
arr=np.arange(5)
print(arr)

[0 1 2 3 4]


In [13]:
arr=np.arange(3,8)
print(arr)

[3 4 5 6 7]


In [14]:
a=np.arange(100,10)
print(a)

[]


In [15]:
a=np.arange(-9,-2)
print(a)

[-9 -8 -7 -6 -5 -4 -3]


In [16]:
arr=np.zeros((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [17]:
arr=np.zeros((4))

In [18]:
print(arr)

[0. 0. 0. 0.]


In [19]:
arr= np.linspace(1,4,4)
print(arr)

[1. 2. 3. 4.]


In [20]:
arr=np.linspace(1,100,5)
print(arr)

[  1.    25.75  50.5   75.25 100.  ]


In [21]:
arr=np.linspace(1,100,4)
print(arr)

[  1.  34.  67. 100.]


In [22]:
arr=np.arange(1,9)
print(arr)

[1 2 3 4 5 6 7 8]


In [23]:
arr=np.arange((2,5))
print(arr)

TypeError: arange: scalar arguments expected instead of a tuple.

In [ ]:
arr=np.empty((2,2))
print(arr)

In [ ]:
arr=np.empty((2,2))
print(arr)

In [ ]:
arr=np.identity(4)
print(arr)

In [ ]:
arr=np.identity(2)
print(arr)

In [ ]:
arr=np.arange(8)
print(arr)

In [ ]:
arr.reshape(2,4)

In [ ]:
arr

In [ ]:
a=arr.reshape(2,4)

In [ ]:
print(a)

In [ ]:
arr=np.linspace(1,2,4)
print(arr)

In [ ]:
a=arr.reshape(2,2)
print(a)

In [ ]:
a.ravel()

In [ ]:
a.shape

In [ ]:
a=[[1,2,3],[4,5,6],[7,1,0]]


In [29]:
ar=np.array(a)

In [ ]:
arr

In [ ]:
arr.sum(axis=0)

In [ ]:
arr.sum(axis=1)

In [ ]:
arr.T

In [ ]:
arr

In [ ]:
for i in arr.flat:
    print(i)

In [ ]:
a=arr.ravel()

In [ ]:
a

In [ ]:
a.argmax()

In [ ]:
a.argmin()

In [ ]:
a.argsort()

In [ ]:
arr

In [ ]:
arr.argmin()

In [ ]:
arr.argmax(axis=0)

In [ ]:
arr.argmax(axis=1)

In [24]:
a=[[1,2],[4,3]]
arr=np.array(a)

In [25]:
arr


array([[1, 2],
       [4, 3]])

In [26]:
arr.argsort()

array([[0, 1],
       [1, 0]], dtype=int64)

In [27]:
arr.argsort(axis=0)

array([[0, 0],
       [1, 1]], dtype=int64)

In [28]:
arr.argsort(axis=1)

array([[0, 1],
       [1, 0]], dtype=int64)

In [30]:
 ar

array([[1, 2],
       [4, 3]])

In [31]:
ar.max()

4

In [35]:
ar.itemsize*ar.size

16

In [36]:
import sys

In [41]:
sys.getsizeof(1)*len(ar)

56

In [38]:
ar

array([[1, 2],
       [4, 3]])

In [39]:
arrr=[[1,2],[3,4]]

In [43]:
sys.getsizeof(1)*len(ar)

56

In [45]:
arrr.itemsize*arrr.size

AttributeError: 'list' object has no attribute 'itemsize'

In [46]:
arr=np.array([1,2])

In [47]:
arr


array([1, 2])

In [48]:
a=[1,2]

In [49]:
sys.getsizeof(1)*len(a)


56

In [53]:
sys.getsizeof(1)*len(a)

56

In [51]:
arr.itemsize*arr.size

8